### ISSUE TITLE
[Bug] Wrong required field name when naming field in JSON property

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#396]
## Informations

Type | Version
---|---
Bug | 4.23.1

****

## Description
I am working on documenting my models and I am using a different name in the generated swagger and the code like this:
```typescript
export default class MyEntity {
	@Required()
	@JsonProperty('my_field')
	myField: string;
}
```
The generated YAML:
```yaml
definitions:
  MyEntity:
    properties:
      my_field:
        type: string
    required:
      - myField # <-- This should be "my_field"
```

## Acceptance criterias
- [ ] Ts.ED version (bug)
