### ISSUE TITLE
[Bug] Multipart Form Swagger - Extra fields

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#398]
## Informations

Type | Version
---|---
Bug | 4.x

****

## Description
When creating a multipart form and generating a swagger, the `in` field of the extra data is not generated correctly. (I am currently acting as if #389 is solved)

There are 3 issues:
1. the `in` field is set to `body` and it should be `formData`
2. a `schema` field is added, but is not allowed
3. the `name` field is missing

Examle, Code:
```typescript
@Controller('/files')
export default class FileCtrl {
	@Post('/upload-file')
	async fileUpload(@MultipartFile() myFile: MulterFile, @BodyParams('string_metadata') metadata: string) {
		// Logic...
	}
}
```

Generated Swagger:
```yaml
paths:
  '/files/upload-file':
    post:
      parameters:
        - in: formData
          name: myFile
          type: file
          description: The file to upload.
        - in: body # <-- This should be formData as well
          required: false
          schema: # <-- This is not allowed
            $ref: '#/definitions/FileCtrlFileUploadPayload'
```

Expected:
```yaml
paths:
  '/files/upload-file':
    post:
      parameters:
        - in: formData
          name: myFile
          type: file
          description: The file to upload.
        - in: formData
          name: string_metadata # <-- This is missing and required
          required: false
```

Thanks!

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)
